### ISSUE TITLE
Update instr_nires for DRP addition

### ISSUE THREAD

**Issue by jmader** [KeckObservatoryArchive/dep-rti#105]
Need to define get_drp_destfile() and get_drp_files_list()

**Comment by joh33-wmko** [comment]
updated instr_nires.py per instr_mosfire.py on vm-koartibuild via nires_drp_addition branch for testing

**Comment by joh33-wmko** [comment]
Lev2 archiving of NIRES NR* files verified via koarti@vm-koartibuild, yesterday.

**Comment by joh33-wmko** [comment]
Changes released to operations on vm-k2koartibuild and has been successfully archiving Lev2 NR* files.
