### ISSUE TITLE
Update wavelengths for acama cameras

### ISSUE THREAD

**Issue by jmader** [KeckObservatoryArchive/dep-rti#98]
instr_guider.py

Currently sets wavelengths for ACAM and ACAMA.  Should include K1ACAMA and K2ACAMA (keep others in case reprocessing is necessary).

**Comment by joh33-wmko** [comment]
updated wavelengths for kNacama in instr_guider.py
- this fix got pushed with issue #100, and is already in place as a workaround on the ops servers.
- awaiting promotion to ops
